extends:
  - "@sinonjs/eslint-config"

plugins:
  - "@sinonjs/no-prototype-methods"

rules:
  "@sinonjs/no-prototype-methods/no-prototype-methods": error
  "jsdoc/require-param-type": off
  "jsdoc/require-jsdoc": off
  "jsdoc/tag-lines": off

overrides:
  - files:
      - "src/**/*.js"
      - "*.mjs"
      - "**/*.mjs"
      - "scripts/**/*.mjs"
      - "test/distribution/browser-global-smoke.js"
      - "test/es2015/check-esm-bundle-is-runnable.js"
    parserOptions:
      sourceType: module
    rules:
      "no-underscore-dangle":
        - error
        - allow:
            - "__dirname"
  - files:
      - "build.cjs"
      - "scripts/**/*.mjs"
      - "test/distribution/browser-global-smoke.js"
      - "test/es2015/check-esm-bundle-is-runnable.js"
    rules:
      "no-console": off
  - files:
      - "*.cjs"
    parserOptions:
      sourceType: script
