#!/usr/bin/env ruby
require "fileutils"
require "pathname"

def add_license(file, version)
  contents = File.read(file)

  File.open(file, "w") do |f|
    f.puts <<PREAMBLE
/**
 * Sinon.JS #{version}, #{Time.now.strftime("%Y/%m/%d")}
 *
 * @author Christian Johansen (christian@cjohansen.no)
 * @author Contributors: https://github.com/cjohansen/Sinon.JS/blob/master/AUTHORS
 *
 * #{File.read("LICENSE").split("\n").join("\n * ")}
 */

PREAMBLE

    f.puts(contents)
  end
end

# This code is an awful hack that is done here only because
# PhantomJS 1.x incorrectly handles "use strict" statement in
# some cases leading to sinon spy executing in a non-strict
# mode, even though it explicitly says otherwise. Since the
# people still use PhantomJS 1.x, this has to remain here
# to add another wrapper with another "use strict" on top
# of UMD bundle packaged by browserify.
def add_use_strict(file)

  contents = File.read(file)

  File.open(file, "w") do |f|
    f.puts("(function () {")
    f.puts("  'use strict';")
    f.puts(contents)
    f.puts("}());")
  end

  file
end

Dir.chdir(File.dirname(__FILE__)) do
  version = File.read("package.json").match(/"version":\s+"(.*)"/)[1]
  version_string = ARGV[0] == "plain" ? "" : "-#{version}"
  output = "pkg/sinon#{version_string}.js"
  browserify = "./node_modules/.bin/browserify"

  FileUtils.mkdir("pkg") unless File.exists?("pkg")
  `#{browserify} -s sinon lib/sinon.js -o #{output}`
  add_license(add_use_strict(output), version)

  File.open("pkg/sinon-ie#{version_string}.js", "w") do |f|
    f.puts(File.read("lib/sinon/util/timers_ie.js"))
    f.puts("\n")
    f.puts(File.read("lib/sinon/util/xhr_ie.js"))
    f.puts(File.read("lib/sinon/util/xdr_ie.js"))
  end

  add_license("pkg/sinon-ie#{version_string}.js", version)

  output_server = "pkg/sinon-server#{version_string}.js"
  server_entry_point = "lib/sinon/util/fake_server_with_clock.js"
  simulate_empty_sinon_core = "-i './lib/sinon/util/core.js'"
  `#{browserify} #{server_entry_point} #{simulate_empty_sinon_core} -s sinon -o #{output_server}`

  add_license("pkg/sinon-server#{version_string}.js", version)
  FileUtils.cp(output, 'pkg/sinon.js')
  FileUtils.cp("pkg/sinon-ie#{version_string}.js", 'pkg/sinon-ie.js')
  FileUtils.cp("pkg/sinon-server#{version_string}.js", 'pkg/sinon-server.js')

  puts "Built Sinon.JS #{version}"
end
