env:
  es6: true

parserOptions:
  ecmaVersion: 2017

extends:
  - ../../../../test/.eslintrc.yml

plugins:
  - local-rules

rules:
  local-rules/no-underscore-dangle: off
  no-underscore-dangle: off
  no-console: off
  no-empty-function: off
  mocha/no-setup-in-describe: off
  no-var: error
  prefer-const: error
  strict: off # cannot use strict mode in RunKit due to it using `with` tricks
