#!/bin/bash

git stash -q --keep-index

# Test prospective commit
git diff-index --cached HEAD --name-only --diff-filter ACMR | egrep '.js$' | xargs $(npm bin)/eslint
RESULT=$?

git stash pop -q

[ $RESULT -ne 0 ] && exit 1
exit 0
