#!/bin/bash +x

# Runs JSCS style checker using definitions in `.jscsrc`
#

# Stash all un-staged changes, we only want to verify staged files
git stash -q --keep-index

# Test prospective commit
git diff-index --cached HEAD --name-only --diff-filter ACMR | egrep '.js$' | xargs $(npm bin)/jscs
RESULT=$?

git stash pop -q

[ $RESULT -ne 0 ] && exit 1
exit 0
