#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# ensure all commands are run from the root dir, for simplicity
cd "$SCRIPT_DIR/.."

# only install git hooks for people developing Sinon
if basename $PWD > /dev/null && [[ -e .git/config ]] ; then
    git config --replace-all core.hooksPath scripts/hooks
fi
