name: Docs Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: docs/package-lock.json
      - name: Install root dependencies
        run: npm ci
        working-directory: .
      - name: Build sinon
        run: npm run build-artifacts
        working-directory: .
      - name: Install docs dependencies
        run: npm ci
        working-directory: docs
      - name: Run docs tests
        run: npm run test:docs
        working-directory: docs
